services:
  web:
    build:
      context: .
    command: bash -c "bundle exec rackup -p 3333 -o '0.0.0.0' -s puma"
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
    volumes:
      - .:/app
    ports:
      - "3333:3333"
